[package]
name = "manialsp"
version = "0.1.0"
authors = ["Vincent Parizet <vincent.parizet@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
flexi_logger = "0.13.2"
tokio = "0.1.7"
bytes = "0.4.12"
tokio-codec = "0.1.0"
tokio-io = "0.1.7"
jsonrpc-core = "12.0.0"
lsp-types = "0.57.2"
serde = "1.0.97"
serde_json = "1.0.40"
